// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pof/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetClaRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetClaRequest) Reset()         { *m = QueryGetClaRequest{} }
func (m *QueryGetClaRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetClaRequest) ProtoMessage()    {}
func (*QueryGetClaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f07510c2931a2e, []int{0}
}
func (m *QueryGetClaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetClaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetClaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetClaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetClaRequest.Merge(m, src)
}
func (m *QueryGetClaRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetClaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetClaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetClaRequest proto.InternalMessageInfo

func (m *QueryGetClaRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetClaResponse struct {
	Cla *Cla `protobuf:"bytes,1,opt,name=Cla,proto3" json:"Cla,omitempty"`
}

func (m *QueryGetClaResponse) Reset()         { *m = QueryGetClaResponse{} }
func (m *QueryGetClaResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetClaResponse) ProtoMessage()    {}
func (*QueryGetClaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f07510c2931a2e, []int{1}
}
func (m *QueryGetClaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetClaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetClaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetClaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetClaResponse.Merge(m, src)
}
func (m *QueryGetClaResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetClaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetClaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetClaResponse proto.InternalMessageInfo

func (m *QueryGetClaResponse) GetCla() *Cla {
	if m != nil {
		return m.Cla
	}
	return nil
}

type QueryAllClaRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllClaRequest) Reset()         { *m = QueryAllClaRequest{} }
func (m *QueryAllClaRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllClaRequest) ProtoMessage()    {}
func (*QueryAllClaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f07510c2931a2e, []int{2}
}
func (m *QueryAllClaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllClaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllClaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllClaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllClaRequest.Merge(m, src)
}
func (m *QueryAllClaRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllClaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllClaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllClaRequest proto.InternalMessageInfo

func (m *QueryAllClaRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllClaResponse struct {
	Cla        []*Cla              `protobuf:"bytes,1,rep,name=Cla,proto3" json:"Cla,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllClaResponse) Reset()         { *m = QueryAllClaResponse{} }
func (m *QueryAllClaResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllClaResponse) ProtoMessage()    {}
func (*QueryAllClaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52f07510c2931a2e, []int{3}
}
func (m *QueryAllClaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllClaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllClaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllClaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllClaResponse.Merge(m, src)
}
func (m *QueryAllClaResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllClaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllClaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllClaResponse proto.InternalMessageInfo

func (m *QueryAllClaResponse) GetCla() []*Cla {
	if m != nil {
		return m.Cla
	}
	return nil
}

func (m *QueryAllClaResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetClaRequest)(nil), "user.pof.pof.QueryGetClaRequest")
	proto.RegisterType((*QueryGetClaResponse)(nil), "user.pof.pof.QueryGetClaResponse")
	proto.RegisterType((*QueryAllClaRequest)(nil), "user.pof.pof.QueryAllClaRequest")
	proto.RegisterType((*QueryAllClaResponse)(nil), "user.pof.pof.QueryAllClaResponse")
}

func init() { proto.RegisterFile("pof/query.proto", fileDescriptor_52f07510c2931a2e) }

var fileDescriptor_52f07510c2931a2e = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4f, 0xc2, 0x30,
	0x18, 0x87, 0xd9, 0x50, 0x0e, 0xf5, 0x5f, 0x28, 0x89, 0x41, 0x62, 0x26, 0x4e, 0xa3, 0xc6, 0x43,
	0x1b, 0xf0, 0xa4, 0x37, 0x24, 0x91, 0xab, 0x72, 0x34, 0x5e, 0x3a, 0x28, 0x63, 0xa6, 0xac, 0x83,
	0x76, 0x46, 0x62, 0xbc, 0xe8, 0x17, 0x30, 0xf1, 0x4b, 0x79, 0x24, 0xf1, 0xe2, 0xc5, 0xc4, 0x80,
	0x1f, 0xc4, 0xb4, 0x9b, 0x61, 0x13, 0xd4, 0xc3, 0x96, 0x2c, 0xfb, 0xbd, 0xef, 0xf3, 0xbc, 0x6f,
	0x0b, 0xd6, 0x02, 0xde, 0xc1, 0xfd, 0x90, 0x0e, 0x86, 0x28, 0x18, 0x70, 0xc9, 0xe1, 0x72, 0x28,
	0xe8, 0x00, 0x05, 0xbc, 0xa3, 0x9e, 0xd2, 0xa6, 0xcb, 0xb9, 0xcb, 0x28, 0x26, 0x81, 0x87, 0x89,
	0xef, 0x73, 0x49, 0xa4, 0xc7, 0x7d, 0x11, 0x65, 0x4b, 0x87, 0x2d, 0x2e, 0x7a, 0x5c, 0x60, 0x87,
	0x08, 0x1a, 0x35, 0xc1, 0x37, 0x15, 0x87, 0x4a, 0x52, 0xc1, 0x01, 0x71, 0x3d, 0x5f, 0x87, 0xe3,
	0xec, 0x8a, 0x02, 0xb5, 0x18, 0x89, 0x3e, 0xed, 0x5d, 0x00, 0x2f, 0x54, 0x41, 0x83, 0xca, 0x3a,
	0x23, 0x4d, 0xda, 0x0f, 0xa9, 0x90, 0x70, 0x15, 0x98, 0x5e, 0xbb, 0x68, 0x94, 0x8d, 0x83, 0x85,
	0xa6, 0xe9, 0xb5, 0xed, 0x13, 0x50, 0x48, 0xa5, 0x44, 0xc0, 0x7d, 0x41, 0xe1, 0x0e, 0xc8, 0xd6,
	0x19, 0xd1, 0xb9, 0xa5, 0x6a, 0x1e, 0x25, 0x8d, 0x91, 0xca, 0xa9, 0xbf, 0xf6, 0x55, 0x4c, 0xa8,
	0x31, 0x96, 0x20, 0x9c, 0x01, 0x30, 0x55, 0x8b, 0x3b, 0xec, 0xa1, 0x68, 0x0e, 0xa4, 0xe6, 0x40,
	0xd1, 0x32, 0xe2, 0x39, 0xd0, 0x39, 0x71, 0x69, 0x5c, 0xdb, 0x4c, 0x54, 0xda, 0x8f, 0x46, 0xac,
	0xf6, 0xdd, 0xfe, 0xa7, 0x5a, 0xf6, 0x77, 0x35, 0xd8, 0x48, 0x49, 0x98, 0x5a, 0x62, 0xff, 0x5f,
	0x89, 0x88, 0x90, 0xb4, 0xa8, 0xbe, 0x1b, 0x60, 0x51, 0x5b, 0xc0, 0x6b, 0xcd, 0x85, 0xe5, 0x34,
	0x71, 0x76, 0xc5, 0xa5, 0xed, 0x3f, 0x12, 0x11, 0xc1, 0xb6, 0x1e, 0x5e, 0x3f, 0x9f, 0xcd, 0x22,
	0x5c, 0xc7, 0x2a, 0x8a, 0xd5, 0xc1, 0xc5, 0x87, 0x87, 0xef, 0xbc, 0xf6, 0x3d, 0xec, 0x82, 0x5c,
	0x9d, 0x91, 0x1a, 0x63, 0x73, 0x71, 0xa9, 0x7d, 0xcf, 0xc5, 0xa5, 0x57, 0x66, 0x6f, 0x68, 0x5c,
	0x01, 0xe6, 0x67, 0x70, 0xa7, 0xc7, 0x2f, 0x63, 0xcb, 0x18, 0x8d, 0x2d, 0xe3, 0x63, 0x6c, 0x19,
	0x4f, 0x13, 0x2b, 0x33, 0x9a, 0x58, 0x99, 0xb7, 0x89, 0x95, 0xb9, 0xdc, 0x72, 0x3d, 0xd9, 0x0d,
	0x1d, 0xd4, 0xe2, 0xbd, 0x69, 0xd9, 0xad, 0x7e, 0xcb, 0x61, 0x40, 0x85, 0x93, 0xd3, 0xf7, 0xec,
	0xe8, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xcc, 0x3e, 0x40, 0xe1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a cla by id.
	Cla(ctx context.Context, in *QueryGetClaRequest, opts ...grpc.CallOption) (*QueryGetClaResponse, error)
	// Queries a list of cla items.
	ClaAll(ctx context.Context, in *QueryAllClaRequest, opts ...grpc.CallOption) (*QueryAllClaResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Cla(ctx context.Context, in *QueryGetClaRequest, opts ...grpc.CallOption) (*QueryGetClaResponse, error) {
	out := new(QueryGetClaResponse)
	err := c.cc.Invoke(ctx, "/user.pof.pof.Query/Cla", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClaAll(ctx context.Context, in *QueryAllClaRequest, opts ...grpc.CallOption) (*QueryAllClaResponse, error) {
	out := new(QueryAllClaResponse)
	err := c.cc.Invoke(ctx, "/user.pof.pof.Query/ClaAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a cla by id.
	Cla(context.Context, *QueryGetClaRequest) (*QueryGetClaResponse, error)
	// Queries a list of cla items.
	ClaAll(context.Context, *QueryAllClaRequest) (*QueryAllClaResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Cla(ctx context.Context, req *QueryGetClaRequest) (*QueryGetClaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cla not implemented")
}
func (*UnimplementedQueryServer) ClaAll(ctx context.Context, req *QueryAllClaRequest) (*QueryAllClaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Cla_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetClaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Cla(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.pof.pof.Query/Cla",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Cla(ctx, req.(*QueryGetClaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClaAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllClaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClaAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.pof.pof.Query/ClaAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClaAll(ctx, req.(*QueryAllClaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.pof.pof.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cla",
			Handler:    _Query_Cla_Handler,
		},
		{
			MethodName: "ClaAll",
			Handler:    _Query_ClaAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pof/query.proto",
}

func (m *QueryGetClaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetClaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetClaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetClaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetClaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetClaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cla != nil {
		{
			size, err := m.Cla.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllClaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllClaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllClaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllClaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllClaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllClaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Cla) > 0 {
		for iNdEx := len(m.Cla) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Cla[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetClaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetClaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cla != nil {
		l = m.Cla.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllClaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllClaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Cla) > 0 {
		for _, e := range m.Cla {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetClaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetClaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetClaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetClaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetClaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetClaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cla", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Cla == nil {
				m.Cla = &Cla{}
			}
			if err := m.Cla.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllClaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllClaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllClaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllClaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllClaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllClaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cla", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cla = append(m.Cla, &Cla{})
			if err := m.Cla[len(m.Cla)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
